### PR TITLE
Enable graphtool to also move internal path vertices

### PR DESCRIPTION
**Pull request by dev2718**
This PR enables the "Move graph nodes" tool to also move internal vertices and fixes a small bug when the primary selection has the wrong type.

### CODE REVIEW

**Comment by otfried** [comment]
Nice, thanks!

**Comment by otfried** [comment]
You don't seem to have your name on your github profile.  If you want to remain anonymous, I can just put "Thanks dev2718" in the Ipe changelog.   Otherwise, write me an email if you prefer first name only etc.

**Comment by dev2718** [comment]
My name is Alexander Firbas - we spoke at GD24. Feel free to credit me as "Alexander Firbas" in the changelog.

**Comment by otfried** [comment]
I did of course recognize what you showed me in Vienna, I just didn't want to violate your choice of not including your name on github.  Thanks again for the code!

**Pull request merged**
